 version: '3.1'
 
 services:
   liberte_d_expression:
     image: liberte_d_expression
     privileged: false
     build:
       context: ./infra
       dockerfile: Dockerfile
     container_name: liberte_d_expression
     restart: always
     ports:
       - "10203:10203"
