 version: '3.1'
 
 services:
  test_aleatoire:
    image: test_aleatoire
    privileged: false
    build:
      context: ./infra/
      dockerfile: Dockerfile
    container_name: test_aleatoire
    restart: always
    ports:
      - "10202:10202"
