 version: '3.1'
 
 services:
   super_vision:
     image: super_vision
     privileged: false
     build:
       context: ./infra
       dockerfile: Dockerfile
     container_name: super_vision
     restart: always
     ports:
       - "10152:8000"
