 version: '3.1'
 
 services:
   stop_censure_v2:
     image: stop_censure_v2
     privileged: false
     build:
       context: ./infra
       dockerfile: Dockerfile
     container_name: stop_censure_v2
     restart: always
     ports:
       - "1337:1337"

