 version: '3.1'
 
 services:
  vip-only-node:
    privileged: false
    build:
      context: ./infra/node-app
    container_name: vip-only-node
    ports:
      - "3000:3000"
    depends_on:
     - vip-only-mongo
    environment:
     - MONGO_URI=mongodb://root:5e409bd6c906e75bc961de62d516ca52@vip-only-mongo:27017/vipOnlyApp?authSource=admin
     - SESSION_SECRET=0A010010D98FDFDJDJHIUAY

  vip-only-mongo:
    privileged: false
    build:
      context: ./infra/mongo-app
    container_name: vip-only-mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: vipOnlyApp
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 5e409bd6c906e75bc961de62d516ca52
