 version: '3.1'

 services:
   aes:
     image: aes
     privileged: false
     build:
       context: ./infra
       dockerfile: Dockerfile
     container_name: aes
     restart: always
     ports:
       - "1337:1337"