version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    restart: always
    ports:
      - "8000:8000"  # Expose Django on port 8000
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
      - MQTT_BROKER_USER=mosquitto  
      - MQTT_BROKER_PASSWORD=12345  
    volumes:
      - ./pepe_ac/:/app/pepe_ac  # Ensure that the pepe_ac folder is mounted
    networks:
      - mqtt_network
    command: ["sh", "-c", "cd /app/pepe_ac && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/config/passwd:/mosquitto/config/passwd  
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - mqtt_network

networks:
  mqtt_network:
    driver: bridge

