 version: '3.1'
 
 services:
  asmble_nationale:
    image: asmble_nationale
    privileged: false
    build:
      context: ./infra/
      dockerfile: Dockerfile
    container_name: asmble_nationale
    restart: always
    ports:
      - "10201:10201"
