 version: '3.1'

 services:
   masteria-2:
     image: masteria
     privileged: false
     build:
       context: ./infra
       dockerfile: Dockerfile
     container_name: masteria-2
     restart: always
     ports:
       - "5000:5000"