version: '3.1'

services:
  secure_authentication:
    image: secure_authentication
    privileged: false
    build:
      context: ./infra/
      dockerfile: Dockerfile
    container_name: secure_authentication
    restart: always
    ports:
      - "10002:80"