 version: '3.1'
 
 services:
   over_under:
     image: over_under
     privileged: false
     build:
       context: ./infra
       dockerfile: Dockerfile
     container_name: over_under
     restart: always
     ports:
       - "10151:8000"
